/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modelos;

import javax.swing.JOptionPane;
import modelos.Funcionario;

/**
 *
 * @author aster
 */
public class telaF extends javax.swing.JFrame {

    /**
     * Creates new form telaF
     */
    public telaF() {
        initComponents();
        setLocationRelativeTo(null);
        jTextArea1Resultado.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2nome = new javax.swing.JLabel();
        jLabel3salario = new javax.swing.JLabel();
        jLabel4quantidadeFilhos = new javax.swing.JLabel();
        jTextField1nome = new javax.swing.JTextField();
        jTextField2salario = new javax.swing.JTextField();
        jTextField3quantidadeFilhos = new javax.swing.JTextField();
        jButton1calcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1Resultado = new javax.swing.JTextArea();
        jLabel4quantidadeFilhos1 = new javax.swing.JLabel();
        jTextField3aumentoSalarial = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("CALCULO FUNCIONÁRIO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2nome.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2nome.setText("NOME:");

        jLabel3salario.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3salario.setText("SALÁRIO:");

        jLabel4quantidadeFilhos.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4quantidadeFilhos.setText("QUANTIDADE DE FILHOS:");

        jTextField1nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1nomeActionPerformed(evt);
            }
        });

        jTextField2salario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2salarioActionPerformed(evt);
            }
        });

        jTextField3quantidadeFilhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3quantidadeFilhosActionPerformed(evt);
            }
        });

        jButton1calcular.setBackground(new java.awt.Color(0, 153, 0));
        jButton1calcular.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1calcular.setText("Calcular");
        jButton1calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1calcularActionPerformed(evt);
            }
        });

        jTextArea1Resultado.setColumns(20);
        jTextArea1Resultado.setRows(5);
        jScrollPane1.setViewportView(jTextArea1Resultado);

        jLabel4quantidadeFilhos1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4quantidadeFilhos1.setText("AUMENTO SALARIAL %:");

        jTextField3aumentoSalarial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3aumentoSalarialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2nome)
                            .addComponent(jLabel3salario)
                            .addComponent(jLabel4quantidadeFilhos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1nome, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(jTextField2salario)
                            .addComponent(jTextField3quantidadeFilhos)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4quantidadeFilhos1)
                        .addGap(14, 14, 14)
                        .addComponent(jTextField3aumentoSalarial)))
                .addGap(18, 18, 18)
                .addComponent(jButton1calcular, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2nome)
                    .addComponent(jTextField1nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3salario)
                    .addComponent(jTextField2salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1calcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4quantidadeFilhos)
                    .addComponent(jTextField3quantidadeFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4quantidadeFilhos1)
                    .addComponent(jTextField3aumentoSalarial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3quantidadeFilhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3quantidadeFilhosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3quantidadeFilhosActionPerformed

    private void jTextField2salarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2salarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2salarioActionPerformed

    private void jButton1calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1calcularActionPerformed

        try {

            Funcionario fu = new Funcionario();

            fu.setNome(jTextField1nome.getText());
            fu.setSalario(Float.parseFloat(jTextField2salario.getText()));
            fu.setNumeroFilhos(Integer.parseInt(jTextField3quantidadeFilhos.getText()));
            fu.setAumento(Integer.parseInt(jTextField3aumentoSalarial.getText()));

            String saida = "";
            saida += ".......................................................................................\n";
            saida += "Dados Do Funcionario:\n";
            saida += "\n";
            saida += ".......................................................................................\n";
            saida += "Nome:\t\t" + fu.getNome() + "\n";
            saida += ".......................................................................................\n";
            saida += "Salário:\t\t" + fu.getSalario() + "\n";
            saida += ".......................................................................................\n";
            saida += "Quantidade Filhos:\t" + fu.getNumeroFilhos() + "\n";
            saida += ".......................................................................................\n";
            saida += "Aumento salarial:\t" + fu.getAumento() + "%" + "\n";
            saida += ".......................................................................................\n";
            saida += "Novo Salario:\t\t" + fu.novoSalario() + "\n";
            saida += ".......................................................................................\n";
            saida += "Valor INSS:\t\t" + fu.calcularInss() + "\n";
            saida += ".......................................................................................\n";
            saida += "Valor Imposto de Renda:\t" + fu.calcularIR() + "\n";
            saida += ".......................................................................................\n";
            saida += "Valor IRPF:\t\t" + fu.calcularIRPF() + "\n";
            saida += ".......................................................................................\n";

            jTextArea1Resultado.setText(saida);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }

    }//GEN-LAST:event_jButton1calcularActionPerformed

    private void jTextField1nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1nomeActionPerformed

    private void jTextField3aumentoSalarialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3aumentoSalarialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3aumentoSalarialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2nome;
    private javax.swing.JLabel jLabel3salario;
    private javax.swing.JLabel jLabel4quantidadeFilhos;
    private javax.swing.JLabel jLabel4quantidadeFilhos1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1Resultado;
    private javax.swing.JTextField jTextField1nome;
    private javax.swing.JTextField jTextField2salario;
    private javax.swing.JTextField jTextField3aumentoSalarial;
    private javax.swing.JTextField jTextField3quantidadeFilhos;
    // End of variables declaration//GEN-END:variables
}
