/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

import Ppersistencia.ClienteDao;
import Ppersistencia.iClienteDao;
import classes.*;
import enumeradores.tipoCliente;
import enumeradores.tipoLogradouro;
import enumeradores.tiposTelefone;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ALUNO
 */
public class teste extends javax.swing.JFrame {

    /**
     * Creates new form teste
     */
    public teste() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("teste");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jButton1)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            ClienteDao teste = new ClienteDao();

            Date dataAtual = new Date();

            endereco testeEndereco = new endereco("Rua 10 Q 20", 255, "Vila Nova", "casa 2", "Goiania", "GO", 74703010, tipoLogradouro.RUA);
            telefone testeTelefone = new telefone("62985738612", tiposTelefone.CELULAR);

            cliente a1 = new cliente(testeTelefone, 1, testeEndereco, "WENDERSONGPI@", tipoCliente.PESSOAFISICA, "06523244105", "12/07/1998", "Social");
            cliente a2 = new cliente(testeTelefone, 2, testeEndereco, "darvintrac@", tipoCliente.PESSOAFISICA, "05911668106", "09/10/2000", "cadastroTeste");
            cliente a3 = new cliente(testeTelefone, 3, testeEndereco, "Nathan!@", tipoCliente.PESSOAJURIDICA, "05911668106", "09/10/2000", "Razão");
            cliente a4 = new cliente(testeTelefone, 4, testeEndereco, "Lucas@", tipoCliente.PESSOAJURIDICA, "05911668166", "10/01/2005", "Razão");
            cliente testeAlterar = new cliente(testeTelefone, 52, testeEndereco, "shvashjsfhsfhsvhjsvhjhj@", tipoCliente.PESSOAJURIDICA, "055131456561", "09/10/2000", "cadastrocliante3");

//            teste.incluir(a1);
//            teste.incluir(a2);
//            teste.incluir(a3);
//            teste.incluir(a4);
//            ArrayList<cliente> listaDeClientes = null;
//            listaDeClientes = teste.obterClientes();
//            String saida = "Lista de Clientes" + "\n";
//
//            for (int i = 0; i < listaDeClientes.size(); i++) {
//
//                saida += "\n" + listaDeClientes.get(i).toString();
//
//            }
            //teste.alterar(testeAlterar, 52);
            teste.excluir(52);
//            jTextArea1.setText(saida);

        } catch (Exception erro) {

            JOptionPane.showMessageDialog(this, erro);
            erro.printStackTrace();

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
